# Generated by Django 4.2.2 on 2023-09-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
